name: Build & Test
"on":
  push:
    branches:
    - '*'
  pull_request:
    branches:
    - '*'
  schedule:
  - cron: 01 13 * * SAT
jobs:
  build:
    name: Build & Test
    strategy:
      matrix:
        os:
        - ubuntu-latest
        - macOS-latest
        - windows-latest
    runs-on: {%raw%}${{ matrix.os }}{%endraw%}
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version: '>=1.21.1'
    - name: Set GOVERSION environment variable (Linux/macOS)
      if: runner.os != 'Windows'
      run: echo "GOVERSION=$(go version)" >> $GITHUB_ENV
    - name: Set GOVERSION environment variable (Windows)
      if: runner.os == 'Windows'
      run: echo "GOVERSION=$(go version)" | Out-File -FilePath $env:GITHUB_ENV -Append
    - name: Build & Test
      run: |
        go build -v
        go test ./...
    - name: Run GoReleaser
      if: runner.os == 'Linux'
      uses: goreleaser/goreleaser-action@v6
      with:
        args: release --snapshot --skip=publish --clean
    - name: Colored Output Test
      if: runner.os == 'Linux'
      shell: script -q -e -c "bash {0}"
      run: go run main.go -- main.go
