name: Release
"on":
  push:
    tags:
    - v*.*.*
permissions:
  contents: write
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - uses: actions/setup-go@v5
    - name: Set GOVERSION environment variable
      run: echo "GOVERSION=$(go version)" >>$GITHUB_ENV
    - name: Release via goreleaser
      uses: goreleaser/goreleaser-action@v6
      with:
        distribution: goreleaser
        version: latest
        args: release --clean
      env:
        GITHUB_TOKEN: {%raw%}${{ secrets.GH_PAT3 }}{%endraw%}
