before:
  hooks:
  - go mod tidy
  - go generate ./...
builds:
- env:
  - CGO_ENABLED=0
  goos:
  - linux
  - windows
  - darwin
  main: main.go
  goarch:
  - amd64
  binary: {{ cookiecutter.project_name }}
  id: {{ cookiecutter.project_name }}
archives:
- format: tar.gz
  name_template: |-
    {{ cookiecutter.project_name }}_ {% raw %}{{- title .Os }}_ {{- if eq .Arch "amd64" }}x86_64
                               {{- else if eq .Arch "386" }}i386
                               {{- else }}
                               {{ .Arch }}
                               {{ end }}
                               {{- if .Arm }}v{{ .Arm }}{{ end }}{% endraw %}

  format_overrides:
  - goos: windows
    format: zip
checksum:
  name_template: checksums.txt
{% raw %}

snapshot:
  name_template: '{{ incpatch .Version }}-next'

{% endraw %}
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'

brews:
- name: {{ cookiecutter.project_name }}
  directory: Formula
  homepage: https://github.com/taylormonacelli/homebrew-tools
  repository:
    owner: taylormonacelli
    name: homebrew-tools
    branch: main

